### ISSUE TITLE
Feature: User can search for a park

### ISSUE THREAD

**Issue by derrick-fleming** [derrick-fleming/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for a park and see results.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to type a specific park on a search bar. They will then be able to see a list of related parks based on their search after clicking "search". User will have ability to "search" on home screen, results screen, or the navigation bar.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-07 at 10 25 54 AM](https://user-images.githubusercontent.com/109825222/200386578-73be28f4-f7e0-4a40-aff7-59f488683426.png)
![Screen Shot 2022-11-07 at 10 27 53 AM](https://user-images.githubusercontent.com/109825222/200386851-abc5f0ae-bda6-414c-87b6-923b956891a9.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create hash routes for screen changes. 
- [x] `renderPage()` based on search results component and route 
- [x] Create a component to hold all of the navigation elements 
- [x] Create a search element within the navigation bar 
- [x] In mobile screen, create an event listener on the 'magnifying glass' icon to open/close search upon click
- [x] Style the navigation bar to match Figma
- [x] Create a component to hold the home screen and 'Search for a park' text.
- [x] Create a search bar element.
- [x] Set `window.location.hash` to be based on `search-results` and `userInputValue`
- [x] Ensure that `userInputValue` gets updated into `window.location.hash` upon search values
- [x] Style components to match the Figma
- [x] Create a component for the '`SearchResults` with a prop of `search` having a value of the user input 
- [x] Check that `renderPage()` will take user to `SearchResults` based on hash/user input
- [x] In the `SearchResults`, display the search bar / search for a park content.
- [x] Style the search results screen to match the Figma.
- [x] Create a component to display the results underneath the search bar
- [x] In `componentDidMount`, complete the following: 
  - [x] `Fetch` results from National Parks API and Wikipedia API based value from `search` props
  - [x] Test that results are being successfully fetched 
  - [x] Create pre-populated list of activities to compare fetched data with 
  - [x] `map` through the retrieved data to create a list of card results. 
  - [x] Use pre-populated list of activities to display only 3-4 activities from list
  - [x] Style the cards to match the Figma including the photos, title, and list of activities.
- [x] Fix `SearchResults` rendering to update search results while on page.
- [x] Create the 'Sorry, no results found' default text if retrieved results `length === 0`
- [x] Test that results are updated and changed based on user inputs
- [x] Update navigation bar search element to include event listeners
- [x] Set hash location on window to be based on `search-results` and `userInputValue` in navigation

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
