### ISSUE TITLE
Feature: User can view updated homepage 

### ISSUE THREAD

**Issue by derrick-fleming** [derrick-fleming/final-project#20]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="199" alt="Screen Shot 2022-11-17 at 3 49 23 PM" src="https://user-images.githubusercontent.com/109825222/202584237-b866b386-3762-45bf-bddb-80b9350f65c6.png">
<img width="599" alt="Screen Shot 2022-11-17 at 3 49 49 PM" src="https://user-images.githubusercontent.com/109825222/202584276-18bf01dd-586b-4c48-ad46-552e3ded712c.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [ ] Update home component to include a `div` for the hero image / search bar component 
- [ ] Add a hero image 
- [ ] Add text: 'Explore.....' 
- [ ] Style the image, text, and search bar to match the Figma 
- [ ] - [ ] Check that search feature still works.
- [ ] Include another section of text that will state: 'Search for.....' 
- [ ] Add a horizontal line (or border) underneath the 'Search for....' 
- [ ] Style the 2nd block of text to match the Figma
- [ ] Ensure that home page looks good in both mobile and desktop views

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
