### ISSUE TITLE
Feature: User can view details of a park

### ISSUE THREAD

**Issue by derrick-fleming** [derrick-fleming/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view details of a park.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Looking at their search results, users will be able to click "Learn More" to see additional details about the specific park. They will be taken to a new view where they will be able to read a description, see a list of popular activities, view the address and map, see a list of fees, and read general weather information. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-07 at 9 07 26 AM](https://user-images.githubusercontent.com/109825222/200371510-b1b43937-8629-477b-b256-a0f6ce615e86.png)
![Screen Shot 2022-11-07 at 9 07 45 AM](https://user-images.githubusercontent.com/109825222/200371522-487ec34a-e54d-4b71-a22f-30e6a7389937.png)
![Screen Shot 2022-11-07 at 9 08 31 AM](https://user-images.githubusercontent.com/109825222/200371705-606a060e-0618-40d6-a015-3857bd74d7ee.png)
![Screen Shot 2022-11-07 at 9 08 44 AM](https://user-images.githubusercontent.com/109825222/200371718-5f5d708f-6408-4881-9211-4403ed4bff92.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update `SearchResults` component `card` to include a button for "See more Details" 
- [x] Include a `Id` on anchor element to keep track of which park is being selected. 
- [x] Create a `ParkDetails` page and component 
- [x] Add `href` to `#details=` and include park name within `hash`
- [x] Check that hash changes are updating
- [x] Add park name, image, description to `ParkDetails` component 
- [x] Include a 'go back' `a` tag to return user to previous results (previous hash destination) 
- [x] Check that park details are being updated and `a` is updating hash
- [x] Add `parkAccordion` that will include 4 rows, each row has a title and a Font Awesome Icon: 
  - [x] Popular Activities [Create a list of pre-rendered activities to display]
  - [x] Address & Directions 
     - [x] Add a address & directions text 
     - [x] Add a `staticGoogleMap` to the directions
  - [x]  Fees
  - [x] Weather Information
- [x] Check that accordion is working and changing based on search results
- [x] Style the park details according to Figma 
- [x] Create a 'hero' image that will include an uploaded background image and title: 'Park Info' with a Font Awesome icon
- [x] Style the 'hero' image according to Figma
- [x] Check that page is responsive in both mobile and desktop views

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
